### PR TITLE
Fix context menu in multiwin sample

### LINKED ISSUE #636: context menus broken
right clicking in the multwin example is supposed to bring up a context menu.

### PR DESCRIPTION
**Pull request by teddemunnik**
Fixes #636 

(Sorry @cmyr, didn't see you had self-assigned the issue until fixing it..)

### CODE REVIEW

**Comment by cmyr** [comment]
no worries at all, I just assumed it would be something more fiddly than this. That said, it's annoying that this was failing silently, I'd have hoped we got some warning when this message was dropped.

If you're interested, I'd be curious to see where that was happening? Who was this being delivered to, and where did it end up getting discarded?

**Comment by teddemunnik** [comment]
It's being delivered to win_handler (see below), so it would be ignored if not using Target::Window. It doesn't seem like there is any logic yet for catching unhandled commands. Perhaps that's something that should be added then? https://github.com/xi-editor/druid/blob/09a23481ebb80c9f9d77c6d5d5e9febba1e99d44/druid/src/win_handler.rs#L287-L298

**Comment by kindlychung** [comment]
Right click on the multiwin example gives me this:

```
cargo run --example multiwin
   Compiling druid v0.5.0 (/home/kaiyin/rustProjects/druid/druid)
    Finished dev [unoptimized + debuginfo] target(s) in 3.80s
     Running `/home/kaiyin/rustProjects/druid/target/debug/examples/multiwin`
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
DEBUG [druid::localization] available locales [en-US, de-DE, fr-CA], current en-US
DEBUG [druid::localization] resolved: [en-US]
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
INFO  [multiwin] Window added, id: WindowId(1)
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/cell.rs:878:9
stack backtrace:
   0:     0x560fa3665c64 - <unknown>
   1:     0x560fa36852bc - <unknown>
   2:     0x560fa3663a93 - <unknown>
   3:     0x560fa3668295 - <unknown>
   4:     0x560fa3667fe2 - <unknown>
   5:     0x560fa36688f2 - <unknown>
   6:     0x560fa36684db - <unknown>
   7:     0x560fa3683c81 - <unknown>
   8:     0x560fa3683aa3 - <unknown>
   9:     0x560fa3651550 - <unknown>
  10:     0x7fc689bcb7ff - <unknown>
  11:     0x7fc68931b936 - <unknown>
  12:     0x7fc689337dcb - g_signal_emit_valist
  13:     0x7fc6893389b3 - g_signal_emit
  14:     0x7fc689b75e53 - <unknown>
  15:     0x7fc689b760ec - <unknown>
  16:     0x7fc689b7ca27 - <unknown>
  17:     0x7fc689a31b88 - <unknown>
  18:     0x7fc689a31f49 - <unknown>
  19:     0x7fc689915639 - <unknown>
  20:     0x7fc689a31e60 - <unknown>
  21:     0x7fc689b8bf19 - <unknown>
  22:     0x7fc689a31e60 - <unknown>
  23:     0x7fc689a32008 - <unknown>
  24:     0x7fc689a3b233 - <unknown>
  25:     0x7fc689a3b755 - gtk_menu_popup
  26:     0x560fa364d8f7 - <unknown>
  27:     0x560fa364b250 - <unknown>
  28:     0x560fa361f6ba - <unknown>
  29:     0x560fa361ca4a - <unknown>
  30:     0x560fa361dafa - <unknown>
  31:     0x560fa361e081 - <unknown>
  32:     0x560fa361df0c - <unknown>
  33:     0x560fa361e9cf - <unknown>
  34:     0x560fa36511c0 - <unknown>
  35:     0x7fc689bcb70b - <unknown>
  36:     0x7fc68931b6e2 - g_closure_invoke
  37:     0x7fc68932f544 - <unknown>
  38:     0x7fc68933799e - g_signal_emit_valist
  39:     0x7fc6893389b3 - g_signal_emit
  40:     0x7fc689b75e53 - <unknown>
  41:     0x7fc689a319d8 - <unknown>
  42:     0x7fc689a33c2b - gtk_main_do_event
  43:     0x7fc68971df19 - <unknown>
  44:     0x7fc689750ff6 - <unknown>
  45:     0x7fc68923084d - g_main_context_dispatch
  46:     0x7fc689230ad0 - <unknown>
  47:     0x7fc689230b73 - g_main_context_iteration
  48:     0x7fc689443b05 - g_application_run
  49:     0x560fa364e96c - <unknown>
  50:     0x560fa364af76 - <unknown>
  51:     0x560fa364a996 - <unknown>
  52:     0x560fa3615471 - <unknown>
  53:     0x560fa3619853 - <unknown>
  54:     0x560fa3614340 - <unknown>
  55:     0x560fa3668dbf - <unknown>
  56:     0x560fa361a39c - <unknown>
  57:     0x7fc688fd01e3 - __libc_start_main
  58:     0x560fa361018e - <unknown>
  59:                0x0 - <unknown>
```

**Comment by xStrom** [comment]
The menu stuff doesn't seem to be fully implemented on Linux.

**Comment by kindlychung** [comment]
Oh, i remember trying this before and it used to work iirc. Maybe someone else can confirm?

**Comment by xStrom** [comment]
The error you posted here contains `MenuDesc::platform_default is not implemented for this platform` and you can check the `MenuDesc::platform_default` function in the code as well.

**Comment by kindlychung** [comment]
Yeah, i checked that. It's not an error, but a warning. `MenuDesc::platform_default` is only implemented for macos, probably because only macos needs it?

The error is caused by `menu.pop_easy`, which is implemented in druid-shell's platform specific code.

**Comment by xStrom** [comment]
The `platform_default` function is missing a Linux implementation which 100% needs to be there. The function contains a comment `we want to explicitly handle all platforms`. That said, the fallback default behavior might work fine on Linux or not, I'm not sure.

Also, yes, the actual crash is caused by a double mut borrow issue. Not sure where that is or why.

Now, as far as fixing the issue, there's a few options.
* You're more than welcome to track down the issue and send the fix.
* Alternatively it would be best to open a new issue for this Linux specific crash so we can be more clear with tracking it.

**Comment by kindlychung** [comment]
#735

**Comment by kindlychung** [comment]
```rust
    /// If this platform always expects windows to have a menu by default,
    /// returns a menu. Otherwise returns `None`.
    #[allow(unreachable_code)]
    pub fn platform_default() -> Option<MenuDesc<T>> {
        #[cfg(target_os = "macos")]
        return Some(MenuDesc::empty().append(sys::mac::application::default()));
        #[cfg(target_os = "windows")]
        return None;

        // we want to explicitly handle all platforms; log if a platform is missing.
        log::warn!("MenuDesc::platform_default is not implemented for this platform.");
        None
    }
```

I don't think linux really expect a window to have a menu by default. linux doesn't even have a default desktop environment.

**Comment by kindlychung** [comment]
```rust
    /// If this platform always expects windows to have a menu by default,
    /// returns a menu. Otherwise returns `None`.
    #[allow(unreachable_code)]
    pub fn platform_default() -> Option<MenuDesc<T>> {
        #[cfg(target_os = "macos")]
        return Some(MenuDesc::empty().append(sys::mac::application::default()));
        #[cfg(any(target_os = "windows", target_os = "linux"))]
        return None;

        // we want to explicitly handle all platforms; log if a platform is missing.
        log::warn!("MenuDesc::platform_default is not implemented for this platform.");
        None
    }
```

Perhaps something like the above will make sense? Just a thought.

**Comment by xStrom** [comment]
I don't really know for sure but that's probably correct yeah. In any case, we should move any discussion of it into the new issue #735.

**Comment by cmyr** [comment]
yes, that looks reasonable to me. This is also unrelated to the crash; the issue with the crash is that something is calling back into druid from the gtk backend while holding a borrow on a `RefCell`.

**Pull request merged**
