### PR TITLE
Change Lens to Lens2 in-place

### PR DESCRIPTION
**Pull request by raphlinus**
The Lens2 version is more flexible, as it allows synthesizing data. This patch updates the Lens trait to that.

### CODE REVIEW

**Comment by Ralith** [comment]
I was just thinking about how this was probably necessary!

**Comment by Ralith** [comment]
It seems a bit inconsistent to have `get` and `with_mut`. Maybe standardize on `with`/`with_mut` or `get`/`get_mut`? I'm weakly in favor of the former.

**Comment by raphlinus** [comment]
Yeah, I think "with" is appropriate. I'll make the change.

**Comment by zaynetro** [comment]
Perfect timing!

**Pull request merged**
