### PR TITLE
Improve multiwin

### LINKED ISSUE #728: ui inconsistency in multiwin example
afbeelding

When the menu count is reduced to 0, one of the windows is still showing `custom` menu.

### PR DESCRIPTION
**Pull request by kindlychung**
* fix #728 
* make use of the command handlers in the `Delegate`

### CODE REVIEW

**Comment by cmyr** [comment]
@kindlychung could you break this into separate PRs? I would like to review the fix without it necessarily including the other changes, thanks!

**Comment by kindlychung** [comment]
@cmyr The added buttons are part of the fix.

**Comment by cmyr** [comment]
I keep on taking a look at this but I'm having trouble following along. Can you maybe explain what your understanding to the problem is, and why this fix makes sense to you? That would help me figure out how to evaluate this. :)

**Comment by kindlychung** [comment]
> I keep on taking a look at this but I'm having trouble following along. Can you maybe explain what your understanding to the problem is, and why this fix makes sense to you? That would help me figure out how to evaluate this. :)

Sure.

The `Delegate` struct now keeps a list of window IDs, once a increment/decrement command arrives, it replays to all the windows, which makes sure all the windows consistently and correctly show the menu entries.

**Comment by kindlychung** [comment]
The inconsistency is described in #728. You can compare the behavior after pulling this pr.

**Comment by jneem** [comment]
Why add two new buttons instead of replacing the old buttons? It seems to me like the old buttons have the incorrect behavior and the new buttons have the correct behavior.

**Comment by kindlychung** [comment]
> Why add two new buttons instead of replacing the old buttons? It seems to me like the old buttons have the incorrect behavior and the new buttons have the correct behavior.

Yeah, that's true. Will delete the old ones.

**Comment by kindlychung** [comment]
Had a lot of trouble rebasing this. Close and open new pr.

**Pull request closed without merging**
