### PR TITLE
Add spacer widget helpers to Flex

### PR DESCRIPTION
**Pull request by cmyr**
This makes it easy to add fixed and flex-size padding between
widgets.

progress on #607

### CODE REVIEW

**Comment by cmyr** [comment]
good Q. it would be limited; you could maybe turn them on or off, but you couldn't, for instance, place them.

**Comment by cmyr** [comment]
okay i've updated the example to let you add spacers.

**Comment by futurepaul** [comment]
Thanks for adding to the example! This is feeling SO expressive for layout now. And the example pretty much solves the "discoverability" aspect for these features.

**Comment by cmyr** [comment]
yea I think so too. Also  I think that the spacer should take a `KeyOrValue`, but that requires changing `SizedBox`.

**Comment by cmyr** [comment]
okay I couldn't help myself: you can now set what the spacer value is, when it is fixed.
Screen Shot 2020-03-11 at 3 18 21 PM

Screen Shot 2020-03-11 at 3 18 37 PM

**Pull request merged**
