### PR TITLE
Set level to 4 on window creation (#43)

### LINKED ISSUE #43: Make mac Window creation smoother
As of #42 the window is now "key" when it is created, meaning that it can respond to mouse move events, but on startup from the command line, there are two visual phases with a transition. The first phase shows the window but behind the terminal (at least on my machine), and the second phase pops it to the front. This is not appealing.

For most apps (ie .app bundles) the activation is handled by Launch Services, not by the app binary itself. Colin and I experimented with various things, changing the order of activation, splitting makeKeyAndOrderFront into its two separate components, etc., but weren't able to figure out the Right Way to do this.

This would be a great starter issue for somebody with low level Cocoa knowledge.

### PR DESCRIPTION
**Pull request by futurepaul**
This fixes #43 as far as I can tell. I just followed @ratmice's ideas and this seemed the correct place to set the level.

On my Mac: without this level it flashes behind the terminal before going in front, with level 4 set it starts up in front of the terminal as expected.

### CODE REVIEW

**Comment by futurepaul** [comment]
Wait!

I'm clearly not paying close enough attention. The window starts in front, but also it remains in front forever. This is not correct, sorry!

**Comment by futurepaul** [comment]
Okay, sorry for all the noise. This works now. (I believe!)

**Comment by cmyr** [comment]
So this is an improvement, but I would second the concern about `setLevel_(0)`. I briefly fired up LLDB and didn't see any unexpected `order:` calls, so I'm not sure about that hunch. I don't have anything more helpful to suggest, though. :(

**Comment by futurepaul** [comment]
I'm pretty stumped on how to do it with that extra setlevel! Fwiw, the [hello_world example here](https://github.com/servo/core-foundation-rs/blob/2aac8fb85b5b114673280e273c04219c0c360e54/cocoa/examples/hello_world.rs) shows the same behind-then-in-front behavior, so I don't think we're doing anything strange that's causing this in the first place.

**Comment by ratmice** [comment]
one more wild guess and i'm stumped,
I would try moving the makeKeyAndOrderFront call, from before app.run()
into a function called from the app.setDelegate_(delegate) method applicationDidFinishLaunching,
or WillFinish...

There is some delegate examples here (but those are window delegates):
https://github.com/servo/core-foundation-rs/blob/2aac8fb85b5b114673280e273c04219c0c360e54/cocoa/examples/fullscreen.rs

using the delegate function applicationDidFinishLaunching or ...WillFinish...
IIRC the main runloop isn't actually running/doing anything with events until app.run().

https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428385-applicationdidfinishlaunching?language=objc

**Comment by cmyr** [comment]
This is resolved in #309.

**Pull request closed without merging**
