### PR TITLE
Add more entries to gitignore.

### PR DESCRIPTION
**Pull request by xStrom**
The `.DS_Store` files showing up in `git status` were annoying me on macOS. I added that and a few others to `.gitignore`.

### CODE REVIEW

**Comment by Finnerale** [comment]
Can we add `.vim/` as well while we are at it?

**Comment by alerque** [comment]
@Finnerale what version of VIM puts anything in a `.vim` folder in project directories? I'm a long time vimmer and not aware that that's a normal usage thing.

I might suggest `*~`, `.*~`, and `tags` as a couple common patterns and a generated file that often gets in my way.

**Comment by Finnerale** [comment]
@alerque Well, I have added an autocmd to load `.vim/init.vim` whenever I enter a directory :sweat_smile: 
That way I can setup keybindings to run build commands on the druid package and execute useful examples.

**Comment by xStrom** [comment]
Okay I added some Vim/Linux entries.

**Comment by alerque** [comment]
Okay. That's fine, but I think I would add that to your personal setup, either through your global `$XDG_CONFIG_HOME/git/ignore` or to your clone of this project via `.git/info/exclude` files. What you are doing is very strongly discouraged by vim in general because it has significant security implications. You or course can do what you want, but this is basically the same as a modeline vulnerability and I wouldn't suggest encouraging it with a shared gitignore.

**Comment by Finnerale** [comment]
@alerque Interesting, didn't know that. Doing what I did is recommended by the fandom wiki (which scores pretty good with search engines) and quite a few plugins. But it should be fine if I make the file name more complex plus a keybinding to generate the file if it does not yet exist. And thanks for the idea with a the local `git/ignore`, did that as well.

**Comment by xStrom** [comment]
Okay I removed `.vim` then.

**Pull request merged**
