### PR TITLE
Add alpha support for images

### PR DESCRIPTION
**Pull request by fishrockz**
This seems better but it would be even nicer if it determined if it was worth loading the alpha channel and then it could save some byte but I don't think it really hurts much. 

Also I don't like committing binary files but that png is smaller than some of the .rs files in that dir.

### CODE REVIEW

**Comment by cmyr** [comment]
is this supposed to look like,

Screen Shot 2020-02-26 at 11 53 00 AM
?

**Comment by fishrockz** [comment]
Yep, I was thinking of setting the background to something more distinctive so it's more obvious. My druid windows backgrounds aren't quite black so it's more obvious

**Comment by fishrockz** [comment]
Screenshot from 2020-02-26 18-35-47
Screenshot from 2020-02-26 18-34-32
Please see before and after.

**Comment by fishrockz** [comment]
I also acured to me that this should be a option for `new` and the binlinier interpolation should be user selectable in the same way that the FillStrat is. shall i add them to this MR?

**Pull request merged**
