### PR TITLE
Allow #[derive(Data)] on empty structs

### PR DESCRIPTION
**Pull request by theduke**
Detect structs with no fields and generate no-op
compare function accordingly.

### CODE REVIEW

**Comment by theduke** [comment]
Useful while iterating. The compile errors are quite off-putting otherwise.

**Comment by cmyr** [comment]
yea this was an open bug, #246. Thanks!

**Comment by theduke** [comment]
Oh, I didn't even see the bug. In that case: 

Fixes #246

**Comment by cmyr** [comment]
I'd love to see tests for this; they can go anywhere in `druid-derive/tests`. The following should all compile:

```rust
#[derive(Clone, Data)]
struct Empty ();

#[derive(Clone, Data)]
struct Empty2 {}

#[derive(Clone, Data)]
enum Items {
One,
Two(),
Three{},
}
```

**Comment by theduke** [comment]
I actually was about to suggest that. 

Do you have a preference for where to put lens tests? `src/lens/test_derive.rs`?

**Comment by theduke** [comment]
Done

**Comment by theduke** [comment]
Ah no I wasn't done yet, still some work to do on enums.

**Comment by cmyr** [comment]
haha sorry. looked like a good checkpoint in any case, so a follow up sounds good.

**Pull request merged**
