### PR TITLE
fix image path in image example

### PR DESCRIPTION
**Pull request by totsteps**

### CODE REVIEW

**Comment by cmyr** [comment]
hmm I'm confused this seems to be working for me?

**Comment by totsteps** [comment]
Oh, wait. You right.
I guess I cd'ed into `examples` dir which broke the path!!

Will close this now.

**Comment by emigr2k1** [comment]
Could this use CARGO_MANIFEST_DIR to avoid that problem?

**Comment by totsteps** [comment]
To be honest I have no idea how `CARGO_MANIFEST_DIR` works!

**Pull request closed without merging**
