### PR TITLE
Complete Either widget

### PR DESCRIPTION
**Pull request by zaynetro**
**Note:** This MR is towards `either` branch. Completes https://github.com/xi-editor/druid/pull/207

I think @raphlinus 's widget is pretty useful already and I would like to have it merged.

The diff is a bit confusing. <s>I don't know why github shows it this way.</s> Raph's branch was a bit outdated.

Relevant commits:

* [Merge origin/master](https://github.com/xi-editor/druid/commit/c9dec270a468a6ad33009d90a52da9af867e1724)
* [Fix wrong branching](https://github.com/xi-editor/druid/commit/4b680eea2ec4b05ebed4dfe56632c7ffd1bb7c8a)
* [Use Lens macro in example](https://github.com/xi-editor/druid/commit/7eba6e43506f0e176144c69244fd4fced8c2fa7a)

### CODE REVIEW

**Comment by cmyr** [comment]
Cool, thanks for this!

There does seem to be something weird going on with this; I've gone and rebased the `either` branch onto the latest master and pushed that. What I would suggest you do here is `git fetch origin` and then `git rebase -i origin/either`, dropping everything but your last two commits, which (I think) are the meat of this PR?

**Comment by cmyr** [comment]
Alternatively I could merge `either` as-is, and you could make a new follow-up PR? Let me know what sounds best to you.

**Comment by zaynetro** [comment]
Either sounds fine to me (not branch name). So I will see tomorrow the status of original PR and do the changes.

**Comment by zaynetro** [comment]
Rebased. Ready for a review.

**Comment by cmyr** [comment]
Thanks!

**Pull request merged**
